#!/usr/bin/env bash

./node_modules/gulp/bin/gulp.js &
./node_modules/browserify/bin/cmd.js \
  -t [coffeeify --no-sourcemaps] \
  -g [uglifyify --no-sourcemaps --compress --screw-ie8 --beautify=false] \
  ./src/scripts/entries/app.coffee -o ./public/js/app.js;
