#!/usr/bin/env bash

./node_modules/watchify/bin/cmd.js -t coffeeify ./src/scripts/entries/app.coffee -o ./public/js/app.js --debug -v &
./node_modules/gulp/bin/gulp.js dev &
./node_modules/nodemon/bin/nodemon.js app.coffee;
